### ISSUE TITLE
Error `java.lang.NoClassDefFoundError: kotlin/time/Instant`

### ISSUE THREAD

**Issue by GangJust** [orchestr7/ktoml#346]
I encountered this issue after upgrading to 0.7.1, and it disappeared when I reverted to 0.7.0.

I checked the [commit history of ktoml](https://github.com/orchestr7/ktoml/commit/827e0468be3524c8eeac14dd66466e84be80610e#diff-7534d65c1dada79f447bd52e6e9a1ab11a09ac7b026eb50967342b0cf7a9acebL18) and found that `kotlinx.datetime.Instant` was changed to `kotlin.time.Instant.`

Could it be that Gradle doesn't support this? Could you please help me?

<img width="1225" height="835" alt="Image" src="https://github.com/user-attachments/assets/bba83575-f46b-47da-a14d-74d4c5af1162" />

**Comment by BOOMeranGG** [comment]
Hi! `kotlinx.datetime.Instant` was deprecated, see https://github.com/Kotlin/kotlinx-datetime?tab=readme-ov-file#deprecation-of-instant

I'd recommend to update your dependencies, if that's possible
